"""
Quantum Leap — Multi-Framework Transpilation & Export Engine
=============================================================
Translates internal CircuitModel into production code for:
1. Qiskit 1.x (Modern primitives, PassManager, AerSimulator)
2. OpenQASM 3.0 (IEEE Standard)
3. OpenQASM 2.0 (Legacy standard)
4. Google Cirq (Idiomatic line qubits and simulator)
5. PennyLane (QNode device representation with expectation values)

Includes circuit optimization telemetry:
- Single-qubit vs two-qubit gate counts
- Circuit depth calculation
- Parameterized gate tracking
- Basis gate decomposition breakdown
"""

import math
from typing import Dict, Any, List
from backend.app.models.schemas import CircuitModel, CircuitInstruction


class QuantumTranspiler:
    """Multi-framework quantum circuit transpilation and telemetry engine."""

    @staticmethod
    def analyze_circuit(circuit: CircuitModel) -> Dict[str, Any]:
        """Compute circuit metrics, depth, and gate distributions."""
        num_qubits = circuit.num_qubits
        insts = circuit.instructions

        total_gates = len(insts)
        single_qubit_gates = 0
        two_qubit_gates = 0
        multi_qubit_gates = 0
        rotation_gates = 0
        measurement_count = 0
        gate_counts: Dict[str, int] = {}

        # Wire depth tracker
        wire_depths = [0] * num_qubits

        for inst in insts:
            g = inst.gate.lower().strip()
            qubits = inst.qubits
            params = inst.params or []

            gate_counts[g] = gate_counts.get(g, 0) + 1

            if g == "measure":
                measurement_count += 1
            elif g in ["rx", "ry", "rz", "cp", "crz", "cu1"]:
                rotation_gates += 1

            if len(qubits) == 1:
                single_qubit_gates += 1
                q = qubits[0]
                if q < num_qubits:
                    wire_depths[q] += 1
            elif len(qubits) == 2:
                two_qubit_gates += 1
                q1, q2 = qubits[0], qubits[1]
                if q1 < num_qubits and q2 < num_qubits:
                    current_max = max(wire_depths[q1], wire_depths[q2])
                    wire_depths[q1] = current_max + 1
                    wire_depths[q2] = current_max + 1
            elif len(qubits) >= 3:
                multi_qubit_gates += 1
                valid_qs = [q for q in qubits if q < num_qubits]
                if valid_qs:
                    current_max = max(wire_depths[q] for q in valid_qs)
                    for q in valid_qs:
                        wire_depths[q] = current_max + 1

        circuit_depth = max(wire_depths) if wire_depths else 0

        # Quantum Volume estimate (heuristic based on depth & qubit width)
        effective_dim = min(num_qubits, circuit_depth)
        quantum_volume_est = 2 ** effective_dim if effective_dim > 0 else 1

        return {
            "num_qubits": num_qubits,
            "total_gates": total_gates,
            "single_qubit_gates": single_qubit_gates,
            "two_qubit_gates": two_qubit_gates,
            "multi_qubit_gates": multi_qubit_gates,
            "rotation_gates": rotation_gates,
            "measurement_count": measurement_count,
            "circuit_depth": circuit_depth,
            "quantum_volume_est": quantum_volume_est,
            "gate_counts": gate_counts,
            "basis_gates": list(gate_counts.keys()),
        }

    @classmethod
    def to_qiskit_1x(cls, circuit: CircuitModel, optimization_level: int = 1) -> str:
        """Transpile to modern Qiskit 1.x standard with primitives and AerSimulator."""
        num_q = circuit.num_qubits
        lines = [
            "# Generated by Quantum Leap Transpilation Engine (Team Gitwolves)",
            "# Target: Qiskit 1.x Architecture",
            "import numpy as np",
            "from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister, transpile",
            "from qiskit.primitives import StatevectorSampler",
            "from qiskit_aer import AerSimulator",
            "",
            f"# Initialize {num_q}-qubit quantum circuit",
            f"qr = QuantumRegister({num_q}, name='q')",
            f"cr = ClassicalRegister({num_q}, name='c')",
            "qc = QuantumCircuit(qr, cr, name='QuantumLeapCircuit')",
            "",
        ]

        for inst in circuit.instructions:
            g = inst.gate.lower().strip()
            q = inst.qubits
            p = inst.params or []

            if g == "h":
                lines.append(f"qc.h(qr[{q[0]}])")
            elif g == "x":
                lines.append(f"qc.x(qr[{q[0]}])")
            elif g == "y":
                lines.append(f"qc.y(qr[{q[0]}])")
            elif g == "z":
                lines.append(f"qc.z(qr[{q[0]}])")
            elif g == "s":
                lines.append(f"qc.s(qr[{q[0]}])")
            elif g == "t":
                lines.append(f"qc.t(qr[{q[0]}])")
            elif g in ["cx", "cnot"]:
                lines.append(f"qc.cx(qr[{q[0]}], qr[{q[1]}])")
            elif g == "cz":
                lines.append(f"qc.cz(qr[{q[0]}], qr[{q[1]}])")
            elif g == "swap":
                lines.append(f"qc.swap(qr[{q[0]}], qr[{q[1]}])")
            elif g in ["ccx", "toffoli"]:
                lines.append(f"qc.ccx(qr[{q[0]}], qr[{q[1]}], qr[{q[2]}])")
            elif g in ["rx", "ry", "rz"] and p:
                lines.append(f"qc.{g}({p[0]}, qr[{q[0]}])")
            elif g in ["cp", "crz", "cu1"] and p:
                lines.append(f"qc.cp({p[0]}, qr[{q[0]}], qr[{q[1]}])")
            elif g == "measure":
                lines.append(f"qc.measure(qr[{q[0]}], cr[{q[0]}])")

        lines.extend([
            "",
            f"# Qiskit 1.x Transpilation (Optimization Level {optimization_level})",
            "backend = AerSimulator()",
            f"transpiled_qc = transpile(qc, backend=backend, optimization_level={optimization_level})",
            "",
            "# Execute using StatevectorSampler primitive",
            "sampler = StatevectorSampler()",
            "job = sampler.run([(transpiled_qc)], shots=1024)",
            "result = job.result()",
            "counts = result[0].data.c.get_counts()",
            "print('Simulation Measurement Counts:', counts)",
        ])

        return "\n".join(lines)

    @classmethod
    def to_openqasm_3(cls, circuit: CircuitModel) -> str:
        """Transpile to IEEE OpenQASM 3.0 specification."""
        num_q = circuit.num_qubits
        lines = [
            "// OpenQASM 3.0 Standard Export",
            "// Generated by Quantum Leap (Team Gitwolves)",
            "OPENQASM 3.0;",
            'include "stdgates.inc";',
            "",
            f"qubit[{num_q}] q;",
            f"bit[{num_q}] c;",
            "",
        ]

        for inst in circuit.instructions:
            g = inst.gate.lower().strip()
            q = inst.qubits
            p = inst.params or []

            if g in ["h", "x", "y", "z", "s", "t"]:
                lines.append(f"{g} q[{q[0]}];")
            elif g in ["cx", "cnot"]:
                lines.append(f"cx q[{q[0]}], q[{q[1]}];")
            elif g == "cz":
                lines.append(f"cz q[{q[0]}], q[{q[1]}];")
            elif g == "swap":
                lines.append(f"swap q[{q[0]}], q[{q[1]}];")
            elif g in ["ccx", "toffoli"]:
                lines.append(f"ccx q[{q[0]}], q[{q[1]}], q[{q[2]}];")
            elif g in ["rx", "ry", "rz"] and p:
                lines.append(f"{g}({p[0]}) q[{q[0]}];")
            elif g in ["cp", "crz", "cu1"] and p:
                lines.append(f"cp({p[0]}) q[{q[0]}], q[{q[1]}];")
            elif g == "measure":
                lines.append(f"c[{q[0]}] = measure q[{q[0]}];")

        return "\n".join(lines)

    @classmethod
    def to_openqasm_2(cls, circuit: CircuitModel) -> str:
        """Transpile to OpenQASM 2.0 legacy format."""
        num_q = circuit.num_qubits
        lines = [
            "OPENQASM 2.0;",
            'include "qelib1.inc";',
            f"qreg q[{num_q}];",
            f"creg c[{num_q}];",
        ]
        for inst in circuit.instructions:
            g = inst.gate.lower().strip()
            q = inst.qubits
            p = inst.params or []
            if g in ["h", "x", "y", "z", "s", "t"]:
                lines.append(f"{g} q[{q[0]}];")
            elif g in ["cx", "cnot"]:
                lines.append(f"cx q[{q[0]}],q[{q[1]}];")
            elif g == "cz":
                lines.append(f"cz q[{q[0]}],q[{q[1]}];")
            elif g == "swap":
                lines.append(f"swap q[{q[0]}],q[{q[1]}];")
            elif g in ["ccx", "toffoli"]:
                lines.append(f"ccx q[{q[0]}],q[{q[1]}],q[{q[2]}];")
            elif g in ["rx", "ry", "rz"] and p:
                lines.append(f"{g}({p[0]}) q[{q[0]}];")
            elif g in ["cp", "crz", "cu1"] and p:
                lines.append(f"cp({p[0]}) q[{q[0]}],q[{q[1]}];")
            elif g == "measure":
                lines.append(f"measure q[{q[0]}] -> c[{q[0]}];")
        return "\n".join(lines)

    @classmethod
    def to_cirq(cls, circuit: CircuitModel) -> str:
        """Transpile to Google Cirq Python syntax."""
        num_q = circuit.num_qubits
        lines = [
            "# Generated by Quantum Leap Transpilation Engine (Team Gitwolves)",
            "# Target: Google Cirq",
            "import cirq",
            "import numpy as np",
            "",
            f"# Define {num_q} line qubits",
            f"qubits = cirq.LineQubit.range({num_q})",
            "circuit = cirq.Circuit()",
            "",
        ]

        for inst in circuit.instructions:
            g = inst.gate.lower().strip()
            q = inst.qubits
            p = inst.params or []

            if g == "h":
                lines.append(f"circuit.append(cirq.H(qubits[{q[0]}]))")
            elif g == "x":
                lines.append(f"circuit.append(cirq.X(qubits[{q[0]}]))")
            elif g == "y":
                lines.append(f"circuit.append(cirq.Y(qubits[{q[0]}]))")
            elif g == "z":
                lines.append(f"circuit.append(cirq.Z(qubits[{q[0]}]))")
            elif g == "s":
                lines.append(f"circuit.append(cirq.S(qubits[{q[0]}]))")
            elif g == "t":
                lines.append(f"circuit.append(cirq.T(qubits[{q[0]}]))")
            elif g in ["cx", "cnot"]:
                lines.append(f"circuit.append(cirq.CNOT(qubits[{q[0]}], qubits[{q[1]}]))")
            elif g == "cz":
                lines.append(f"circuit.append(cirq.CZ(qubits[{q[0]}], qubits[{q[1]}]))")
            elif g == "swap":
                lines.append(f"circuit.append(cirq.SWAP(qubits[{q[0]}], qubits[{q[1]}]))")
            elif g in ["ccx", "toffoli"]:
                lines.append(f"circuit.append(cirq.TOFFOLI(qubits[{q[0]}], qubits[{q[1]}], qubits[{q[2]}]))")
            elif g == "rx" and p:
                lines.append(f"circuit.append(cirq.rx({p[0]})(qubits[{q[0]}]))")
            elif g == "ry" and p:
                lines.append(f"circuit.append(cirq.ry({p[0]})(qubits[{q[0]}]))")
            elif g == "rz" and p:
                lines.append(f"circuit.append(cirq.rz({p[0]})(qubits[{q[0]}]))")
            elif g in ["cp", "crz", "cu1"] and p:
                lines.append(f"circuit.append(cirq.CZPowGate(exponent={p[0]} / np.pi)(qubits[{q[0]}], qubits[{q[1]}]))")
            elif g == "measure":
                lines.append(f"circuit.append(cirq.measure(qubits[{q[0]}], key='m{q[0]}'))")

        lines.extend([
            "",
            "# Simulate using Cirq Simulator",
            "simulator = cirq.Simulator()",
            "result = simulator.run(circuit, repetitions=1024)",
            "print('Cirq Measurement Results:')",
            "print(result.histogram(key='m0') if num_qubits == 1 else result)",
        ])

        return "\n".join(lines)

    @classmethod
    def to_pennylane(cls, circuit: CircuitModel) -> str:
        """Transpile to PennyLane QNode device representation."""
        num_q = circuit.num_qubits
        lines = [
            "# Generated by Quantum Leap Transpilation Engine (Team Gitwolves)",
            "# Target: PennyLane Quantum Machine Learning",
            "import pennylane as qml",
            "import numpy as np",
            "",
            f"# Define {num_q}-qubit device using PennyLane default.qubit simulator",
            f"dev = qml.device('default.qubit', wires={num_q})",
            "",
            "@qml.qnode(dev)",
            "def quantum_circuit():",
        ]

        has_gates = False
        for inst in circuit.instructions:
            g = inst.gate.lower().strip()
            q = inst.qubits
            p = inst.params or []

            if g == "h":
                lines.append(f"    qml.Hadamard(wires={q[0]})")
                has_gates = True
            elif g == "x":
                lines.append(f"    qml.PauliX(wires={q[0]})")
                has_gates = True
            elif g == "y":
                lines.append(f"    qml.PauliY(wires={q[0]})")
                has_gates = True
            elif g == "z":
                lines.append(f"    qml.PauliZ(wires={q[0]})")
                has_gates = True
            elif g == "s":
                lines.append(f"    qml.S(wires={q[0]})")
                has_gates = True
            elif g == "t":
                lines.append(f"    qml.T(wires={q[0]})")
                has_gates = True
            elif g in ["cx", "cnot"]:
                lines.append(f"    qml.CNOT(wires=[{q[0]}, {q[1]}])")
                has_gates = True
            elif g == "cz":
                lines.append(f"    qml.CZ(wires=[{q[0]}, {q[1]}])")
                has_gates = True
            elif g == "swap":
                lines.append(f"    qml.SWAP(wires=[{q[0]}, {q[1]}])")
                has_gates = True
            elif g in ["ccx", "toffoli"]:
                lines.append(f"    qml.Toffoli(wires=[{q[0]}, {q[1]}, {q[2]}])")
                has_gates = True
            elif g == "rx" and p:
                lines.append(f"    qml.RX({p[0]}, wires={q[0]})")
                has_gates = True
            elif g == "ry" and p:
                lines.append(f"    qml.RY({p[0]}, wires={q[0]})")
                has_gates = True
            elif g == "rz" and p:
                lines.append(f"    qml.RZ({p[0]}, wires={q[0]})")
                has_gates = True
            elif g in ["cp", "crz", "cu1"] and p:
                lines.append(f"    qml.ControlledPhaseShift({p[0]}, wires=[{q[0]}, {q[1]}])")
                has_gates = True

        if not has_gates:
            lines.append("    pass")

        lines.extend([
            f"    return qml.probs(wires=range({num_q}))",
            "",
            "# Execute and print measurement probability distribution",
            "probabilities = quantum_circuit()",
            "print('PennyLane Quantum State Probabilities:')",
            f"for i, p in enumerate(probabilities):",
            f"    print(f'|{{i:0{num_q}b}}> : {{float(p):.4f}}')",
        ])

        return "\n".join(lines)

    @classmethod
    def transpile_all(cls, circuit: CircuitModel, optimization_level: int = 1) -> Dict[str, Any]:
        """Generate exports for all 5 frameworks alongside circuit telemetry."""
        telemetry = cls.analyze_circuit(circuit)
        return {
            "telemetry": telemetry,
            "qiskit": cls.to_qiskit_1x(circuit, optimization_level),
            "openqasm3": cls.to_openqasm_3(circuit),
            "openqasm2": cls.to_openqasm_2(circuit),
            "cirq": cls.to_cirq(circuit),
            "pennylane": cls.to_pennylane(circuit),
        }
